version: "3.7"
services:
  phaser-react-boilerplate:
    image: node:19-alpine3.16
    container_name: phaser-react-boilerplate
    ports:
      - 5173:5173
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install && npm run dev"
